#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems: Towards Deep Learning State-of-the-Art                         #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /config.yml                                                                         #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Recommender-Systems                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday December 1st 2022 05:01:51 pm                                              #
# Modified   : Sunday December 25th 2022 10:38:41 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
mode: test
# ------------------------------------------------------------------------------------------------ #
prod:
  core:
    logging:
      version: 1
      formatters:
        console:
          format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
          datefmt: "%m/%d/%Y %I:%M:%S %p"
        file:
          format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s] : %(message)s"
          datefmt: "%m/%d/%Y %I:%M:%S %p"
      handlers:
        console:
          class: "logging.StreamHandler"
          level: "DEBUG"
          formatter: "console"
          stream: "ext://sys.stderr"
        file:
          class: logging.handlers.TimedRotatingFileHandler
          formatter: file
          when: midnight
          interval: 1
          backupCount: 0
          level: "DEBUG"
          filename: logs/prod/recsys.log
      root:
        level: "DEBUG"
        handlers: ["console", "file"]
      disable_existing_loggers: False

  data:
    database:
      sqlite:
        location: data/prod/recsys.sqlite3
      shelve:
        location: data/prod/recsys.odb

# ------------------------------------------------------------------------------------------------ #
dev:
  core:
    logging:
      version: 1
      formatters:
        console:
          format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
          datefmt: "%m/%d/%Y %I:%M:%S %p"
        file:
          format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s] : %(message)s"
          datefmt: "%m/%d/%Y %I:%M:%S %p"
      handlers:
        console:
          class: "logging.StreamHandler"
          level: "DEBUG"
          formatter: "console"
          stream: "ext://sys.stderr"
        file:
          class: logging.handlers.TimedRotatingFileHandler
          formatter: file
          when: midnight
          interval: 1
          backupCount: 0
          level: "DEBUG"
          filename: logs/dev/recsys.log
      root:
        level: "DEBUG"
        handlers: ["console", "file"]
      disable_existing_loggers: False

  data:
    database:
      sqlite:
        location: data/dev/recsys.sqlite3
      shelve:
        location: data/dev/recsys.odb

# ------------------------------------------------------------------------------------------------ #
test:
  core:
    logging:
      version: 1
      formatters:
        console:
          format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
          datefmt: "%m/%d/%Y %I:%M:%S %p"
        file:
          format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s] : %(message)s"
          datefmt: "%m/%d/%Y %I:%M:%S %p"
      handlers:
        console:
          class: "logging.StreamHandler"
          level: "DEBUG"
          formatter: "console"
          stream: "ext://sys.stderr"
        file:
          class: logging.handlers.TimedRotatingFileHandler
          formatter: file
          when: midnight
          interval: 1
          backupCount: 0
          level: "DEBUG"
          filename: logs/test/recsys.log
      root:
        level: "DEBUG"
        handlers: ["console", "file"]
      disable_existing_loggers: False

  data:
    database:
      sqlite:
        location: tests/data/recsys.sqlite3
      shelve:
        location: tests/data/recsys.odb