#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems: Towards Deep Learning State-of-the-Art                         #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /recsys/core/workflow/config/01_movielens25m_prep.yml                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Recommender-Systems                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday December 5th 2022 02:42:49 pm                                                #
# Modified   : Sunday December 18th 2022 06:18:21 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
#                                 MOVIELENS 25M DATASET ETL                                        #
# ================================================================================================ #
# This short pipeline of tasks downloads, extracts, converts the ratings data to pickle format     #
# for faster loading, and loads the data into the production, development and test environments.   #
# ------------------------------------------------------------------------------------------------ #
prep:
  env: prod
  name: data_preparation_pipeline_prod
  description: Performs Data Preparation for Production Environment
  tasks:
  # ---------------------------------------------------------------------------------------------- #
  #                                   TRAIN TEST SPLIT                                             #
  # ---------------------------------------------------------------------------------------------- #
    train_test_split:
      name: train_test_split_prod
      description: Split Production Dataset into Train and Test Set
      operator: prod.train_test_split
      params:
        input:
          kind: dataset
          name: movielens25m_ratings_dataset_prod
        operator:
          split_var: 'timestamp'
          train_size: 0.80
        output:
          kind: dict
          train:
            kind: dataset
            name: movielens25m_ratings_dataset_prod_train
            description: MovieLens25M Production Train Ratings Dataset
            mode: prod
            stage: split
            filename: ratings_train.pkl
          test:
            kind: dataset
            name: movielens25m_ratings_dataset_prod_test
            description: MovieLens25M Production Test Ratings Dataset
            mode: prod
            stage: split
            filename: ratings_test.pkl
  # ---------------------------------------------------------------------------------------------- #
  #                                    CENTER RATINGS                                              #
  # ---------------------------------------------------------------------------------------------- #
    center_train_data:
      name: center_prod_train_ratings_data
      description: Center Production Train Ratings Dataset by Mean User Rating
      operator: prod.center
      params:
        input:
          kind: dataset
          name: movielens25m_ratings_dataset_prod_train
        operator:
          var: rating
          group_var: userId
          out_var: rating_centered
        output:
          kind: dataset
          name: movielens25m_ratings_dataset_prod_train_centered
          description: MovieLens25M Production Train Ratings Data Centered
          mode: prod
          stage: interim
          filename: ratings_train_centered.pkl
  # ---------------------------------------------------------------------------------------------- #
  #                             AGGREGATE USER RATINGS AVERAGE                                     #
  # ---------------------------------------------------------------------------------------------- #
    aggregate_train:
      name: prod_train_average_user_ratings
      description: Production Train Average User Ratings
      operator: prod.aggregate
      params:
        input:
          kind: dataset
          name: movielens25m_ratings_dataset_prod_train
        operator:
          var: rating
          group_var: userId
          out_var: ave_rating
        output:
          kind: dataset
          name: movielens25m_ave_user_ratings_dataset_prod_train
          description: MovieLens25M Production Train Average User Ratings
          mode: prod
          stage: interim
          filename: ave_user_ratings_train.pkl



