#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems: Towards Deep Learning State-of-the-Art                         #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /recsys/core/workflow/config/01_movielens25m_datasets.yml                           #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Recommender-Systems                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday December 5th 2022 02:42:49 pm                                                #
# Modified   : Monday December 12th 2022 02:51:32 am                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
#                            MOVIELENS 25M DATASET PREPROCESSING                                   #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                      DATA STAGING                                                #
# ------------------------------------------------------------------------------------------------ #
# This short pipeline of tasks downloads, extracts, and converts the ratings data to pickle        #
# format for faster loading.                                                                       #
# ------------------------------------------------------------------------------------------------ #
staging:
  name: stage_movielens25m_datasets
  description: Extracts MovieLens25M data from GroupLens website, Transforms data into pickle format for downstream processing.
  tasks:
    download:
      name: download_extract_movielens25m
      description: Download and extract MovieLens25M data from GroupLens website.
      operator: downloader
      params:
        operator:
          url: https://files.grouplens.org/datasets/movielens/ml-25m.zip
          destination: data/movielens25m/raw
        output:
        - kind: fileset
          name: movielens25m_genome-scores
          description: Contains movie-tag relevance data
          datasource: movielens25m
          workspace: data
          stage: raw
          filename: genome-scores.csv
        - kind: fileset
          name: movielens25m_genome-tags
          description: Provides the tag descriptions for the tag IDs in the genome file
          datasource: movielens25m
          workspace: data
          stage: raw
          filename: genome-tags.csv
        - kind: fileset
          name: movielens25m_links
          description: Identifiers that can be used to link to other sources of movie data.
          datasource: movielens25m
          workspace: data
          stage: raw
          filename: links.csv
        - kind: fileset
          name: movielens25m_movies
          description: Movie information
          datasource: movielens25m
          workspace: data
          stage: raw
          filename: movies.csv
        - kind: fileset
          name: movielens25m_ratings
          description: Contains movie ratings, one rating for one movie per row.
          datasource: movielens25m
          workspace: data
          stage: raw
          filename: ratings.csv
        - kind: fileset
          name: movielens25m_tags
          description: One tag per one movie per row
          datasource: movielens25m
          workspace: data
          stage: raw
          filename: tags.csv
        force: False
    pickle:
      name: pickle_raw_ratings_data
      description: Save a copy of the ratings file in pickle format for faster  downstream loading.
      operator: pickler
      params:
        input:
          kind: fileset
          name: movielens25m_ratings
        output:
        - kind: fileset
          name: movielens25m_ratings_pkl
          description: Movielens Ratings data in Pickle format.
          datasource: movielens25m
          workspace: data
          stage: raw
          filename: ratings.pkl
        force: False
# ------------------------------------------------------------------------------------------------ #
#                               PRODUCTION DATA GEN                                                #
# ------------------------------------------------------------------------------------------------ #
# Generation and preprocessing of data in the production environment.                              #
# ------------------------------------------------------------------------------------------------ #
prod:
  name: prod_dataset
  description: Generate and Preprocess Data for Production Environment
  tasks:
    gen_dataset:
      name: gen_prod_dataset
      description: Generate MovieLens25M Dataset for Production Environment
      operator: prod.gen_dataset
      params:
        input:
          kind: fileset
          name: movielens25m_ratings_pkl
        operator:
          cluster: True
          cluster_by: userId
          frac: 1
          shuffle: True
          replace: False
          random_state: 55
        output:
          kind: dataset
          name: movielens25m_ratings_dataset_prod
          description: Movielens25M Ratings Dataset
          datasource: movielens25m
          workspace: prod
          stage: input
          filename: ratings.pkl
        force: False
    train_test_split:
      name: train_test_split_prod
      description: Split Production Dataset into Train and Test Set
      operator: prod.train_test_split
      params:
        input:
          kind: dataset
          name: movielens25m_ratings_dataset_prod
        operator:
          train_size: 0.80
        output:
          kind: tts_split_dataset
          train:
            kind: dataset
            name: movielens25m_ratings_dataset_prod_train
            description: MovieLens25M Production Train Ratings Dataset
            workspace: prod
            stage: split
            filename: ratings_train.pkl
          test:
            kind: dataset
            name: movielens25m_ratings_dataset_prod_test
            description: MovieLens25M Production Test Ratings Dataset
            workspace: prod
            stage: split
            filename: ratings_test.pkl
    center_train_data:
      name: center_prod_train_ratings_data
      description: Center Production Train Ratings Dataset by Mean User Rating
      operator: prod.center
      params:
        input:
          kind: dataset
          name: movielens25m_ratings_dataset_prod_train
        operator:
          var: rating
          group_var: userId
          out_var: rating_centered
        output:
          kind: dataset
          name: movielens25m_ratings_dataset_prod_train_centered
          description: MovieLens25M Production Train Ratings Data Centered
          workspace: prod
          stage: interim
          filename: ratings_train_centered.pkl
    aggregate_train:
      name: prod_train_average_user_ratings
      description: Production Train Average User Ratings
      operator: prod.aggregate
      params:
        input:
          kind: dataset
          name: movielens25m_ratings_dataset_prod_train
        operator:
          var: rating
          group_var: userId
          out_var: ave_rating
        output:
          kind: dataset
          name: movielens25m_ave_user_ratings_dataset_prod_train
          description: MovieLens25M Production Train Average User Ratings
          workspace: prod
          stage: interim
          filename: ave_user_ratings_train.pkl



