#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems: Towards Deep Learning State-of-the-Art                         #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /etl.yml                                                                            #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Recommender-Systems                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday November 25th 2022 03:01:44 pm                                               #
# Modified   : Friday November 25th 2022 03:17:36 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
name: etl
description: Extract Transform and Load for MovieLens20M Dataset
steps:
  1:
    name: download_movielens20m
    description: Downloads MovieLens20M Dataset from Kaggle
    module: recsys.core.workflow.operators
    operator: KaggleDownloader
    params:
      kaggle_filepath: grouplens/movielens-20m-dataset
      destination: data/ext
      force: False

  2:
    name: dezip_movielens20m
    description: UnZips MovieLens20M Dataset
    module: recsys.core.workflow.operators
    operator: DeZipper
    params:
      zipfilepath: data/ext/movielens-20m-dataset.zip
      destination: data/raw
      members:
        - rating.csv
      force: False

  3:
    name: pickle_dataset
    description: Pickles ratings dataset
    module: recsys.core.workflow.operators
    operator: Pickler
    params:
      infilepath: data/raw/rating.csv
      outfilepath: data/raw/rating.pkl
      infile_format: csv
      index_col: False
      encoding: utf-8
      low_memory: False
      usecols:
        - userId
        - movieId
        - rating