#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems: Towards Deep Learning State-of-the-Art                         #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /process.yaml                                                                       #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Recommender-Systems                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday November 17th 2022 03:18:06 am                                             #
# Modified   : Friday November 18th 2022 11:11:31 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
---
# ================================================================================================ #
#                                         ETL                                                      #
# ================================================================================================ #

name: movielens20m_preprocess
description: Prepares the Rating Data for Collaborative Filtering Recommendation

# ------------------------------------------------------------------------------------------------ #
#                                  PREPROCESSING STEPS                                             #
# ------------------------------------------------------------------------------------------------ #
steps:
  1:
    name: download_movielens20m
    description: Downloads MovieLens20M data from Kaggle website.
    module: recsys.core.dpl.etl
    operator: KaggleDownloader
    params:
      kaggle_filepath: grouplens/movielens-20m-dataset
      destination: data/movielens20m/ext
      force: False

  2:
    name: dezip_movielens20m
    description: UnZips MovieLens20M Dataset
    module: recsys.core.dpl.etl
    operator: DeZipper
    params:
      zipfilepath: data/movielens20m/ext/movielens-20m-dataset.zip
      destination: data/movielens20m/raw
      members:
        - rating.csv
      force: False

  3:
    name: pickle_dataset
    description: Pickles ratings dataset
    module: recsys.core.dpl.etl
    operator: Pickler
    params:
      infilepath: data/movielens20m/raw/rating.csv
      outfilepath: data/movielens20m/raw/rating.pkl
      infile_format: csv
      index_col: False
      encoding: utf-8
      low_memory: False
      usecols:
        - userId
        - movieId
        - rating