#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems: Towards Deep Learning State-of-the-Art                         #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /cf.yml                                                                             #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Recommender-Systems                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday November 26th 2022 12:17:05 pm                                             #
# Modified   : Wednesday November 30th 2022 10:24:14 pm                                            #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
# Collaborative Filtering Preprocessing Configuration Module"
name: collabfilter_data_prep
description: Data Preprocessing for Collaborative Filter Recommender
operator_module: recsys.methods.neighborhood.workflow.operators
steps:
  1: CreateDataset
  2: TrainTestSplit
  3: TrainDataCentralizer
  4: TestDataCentralizer
  5: TrainUser
  6: TestUser
