#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems: Towards Deep Learning State-of-the-Art                         #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /process.yaml                                                                       #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Recommender-Systems                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday November 17th 2022 03:18:06 am                                             #
# Modified   : Sunday November 20th 2022 09:15:09 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
---
# ================================================================================================ #
#                                      PREPROCESS                                                  #
# ================================================================================================ #

name: movielens20m_preprocess
description: Prepares the Rating Data for Collaborative Filtering Recommendation
io_module: recsys.core.services.io
io_service: IOService

# ------------------------------------------------------------------------------------------------ #
#                                  PREPROCESSING STEPS                                             #
# ------------------------------------------------------------------------------------------------ #
steps:
  1:
    name: create_rating_dataset
    description: Creates rating dataset
    module: recsys.collaborative.data.process
    operator: CreateDataset
    params:
      input_file_params: tests/data/etl/movielens20m/raw/rating.pkl
      input_dataset_params: None
      output_dataset_params:
        name: rating
        env: test
        stage: interim
        version: !!int "1"
        description: Rating Dataset
        version_control: !!bool "true"

  2:
    name: train_test_split
    description: Train Test Split (Clustered on UserId)
    module: recsys.collaborative.data.process
    operator: TrainTestSplit
    params:
      input_dataset_params:
        name: rating
        env: test
        stage: interim
        version: !!int "1"
        description: Rating Dataset
      output_dataset_params:
        train:
          name: train
          env: test
          stage: interim
          version: !!int "1"
          description: MovieLens20M Training Set (for Test Env)
        test:
          name: test
          env: test
          stage: interim
          version: !!int "1"
          description: MovieLens20M Test Set (for Test Env)
        clustered: !!bool "true"
        clustered_by: userId
        train_proportion: !!float "0.8"
        random_state: !!int "20"
        version_control: !!bool "true"

  3:
    name: ratings_adjuster
    description: Ratings Adjuster - Centers the Ratings
    module: recsys.collaborative.data.process
    operator: RatingsAdjuster
    params:
      input_dataset_params:
        name: train
        env: test
        stage: interim
        version: !!int "1"
        description: MovieLens20M Training Set (for Test Env)
      output_dataset_params:
        name: train_ratings_centered
        env: test
        stage: interim
        version: !!int "1"
        description: MovieLens20M Training Set w/ Ratings Centered (for Test Env)

  4:
    name: average_rating
    description: Average Ratings by User
    module: recsys.collaborative.data.process
    operator: User
    params:
      input_dataset_params:
        name: train
        env: test
        stage: interim
        version: !!int "1"
        description: MovieLens20M Training Set (for Test Env)
      output_dataset_params:
        name: train_average_ratings
        env: test
        stage: interim
        version: !!int "1"

  5:
    name: phi
    description: User Neighbor Dataset = Contains Every Combination of Users in the Dataset
    module: recsys.collaborative.data.process
    operator: Phi
    params:
      input_dataset_params:
        name: train
        env: test
        stage: interim
        version: !!int "1"
        description: MovieLens20M Training Set (for Test Env)
      output_dataset_params:
        name: train_phi
        env: test
        stage: interim
        version: !!int "1"
        description: User Neighbor Dataset = Contains Every Combination of Users in the Dataset

  6:
    name: weights
    description: User - User Weights
    module: recsys.collaborative.data.process
    operator: UserWeights
    params:
      input_dataset_params:
        name: train_user_neighbor
        env: test
        stage: interim
        version: !!int "1"
        description: User Neighbor Dataset = Contains Every Combination of Users in the Dataset
      output_dataset_params:
        name: train_weights
        env: test
        stage: interim
        version: !!int "1"
        description: User - User Weights

  7:
    name: data_integrator
    description: Integrates weight, rating, and user data
    module: recsys.collaborative.data.process
    operator: DataIntegrator
    params:
      input_dataset_params:
        phi:
          name: train_phi
          env: test
          stage: interim
          version: !!int "1"
          description: User Neighbor Dataset = Contains Every Combination of Users in the Dataset
        weights:
          name: train_weights
          env: test
          stage: interim
          version: !!int "1"
          description: User - User Weights
        ratings:
          name: train_ratings_centered
          env: test
          stage: interim
          version: !!int "1"
          description: MovieLens20M Training Set w/ Ratings Centered (for Test Env)
      output_dataset_params:
        name: train_master
        env: test
        stage: interim
        version: !!int "1"
        description: Master Train File
